### PR TITLE
chore: fix typos

### PR DESCRIPTION
**Pull request by xiaolou86**

### CODE REVIEW

**Comment by l-monninger** [comment]
@xiaolou86 Are you still working on this?

**Comment by xiaolou86** [comment]
@l-monninger Yeah, and as a beginner I start from typo fix. What do you mean?

**Comment by l-monninger** [comment]
Just wanted to see if you were planning to add any more. So, yes, this is all for now?

**Comment by xiaolou86** [comment]
Yes, that's all for now. Thank you very much.

**Pull request closed without merging**
